name: Build and upload jar as asset
on:
    release:
        types:
            - released

jobs:
    build-and-upload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout latest commit
              uses: actions/checkout@v3
            - name: validate gradle wrapper
              uses: gradle/wrapper-validation-action@v1
            - name: setup jdk 17
              uses: actions/setup-java@v3
              with:
                java-version: 17
                distribution: 'microsoft'
            - name: make gradle wrapper executable
              run: chmod +x ./gradlew
            - name: build
              run: ./gradlew build
            - name: Hash jar
              run: sha256sum build/libs/*[^-dev].jar
            - name: Upload asset
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: build/libs/*[^-dev].jar
                  tag: ${{ github.ref }}
                  file_glob: true